### ISSUE TITLE
检测是否为好友，不是实时的。

### ISSUE THREAD

**Issue by senioi** [Miyakowww/CocoaFramework2#1]
您好，感谢您的付出，为了我们带来了一个简洁且开箱即用的库。
请问如何实时检测对方是否为好友呢？
我使用以下代码：
`    public static async Task RunAsync(MessageSource src, QMessage msg)
    {
                if (!src.User.IsFriend) { 
                await src.SendReplyExAsync(msg, true, $"\n您当前不是我的好友，请加我为好友。");
                return;
                }
}`
当QQ用户添加机器人为好友后，再次检测，还是 IsFriend=false，必须重启该程序后（不是重启mirai），检测才正常。请问是不是有缓存，或者有类似实时获取是否为好友的函数呀。

**Comment by Miyakowww** [comment]
可以先手动调用BotInfo.ReloadFriends()，后续版本会加入自动刷新

**Comment by Miyakowww** [comment]
#448e6c4
