### ISSUE TITLE
支持好友请求等 Event

### ISSUE THREAD

**Issue by Kgym-Hina** [Miyakowww/CocoaFramework2#2]
找到了这个很棒的项目！
我在尝试用这个构建群内机器人时遇到了一些问题。希望能在他人加好友的时候能在程序内处理通过与否。

**Comment by Miyakowww** [comment]
可以通过 BotAPI.OnNewFriendRequest 注册加好友事件，通过 NewFriendRequestEvent.Response 扩展方法处理请求
