### ISSUE TITLE
根据Doc中“实现简单应答”的流程没有得到对应的结果

### ISSUE THREAD

**Issue by CHKZL** [Miyakowww/CocoaFramework2#4]
我在一个空白项目中，根据文档流程正确启动mirai登陆然后在Nuget安装完cocoa，在Program.cs和Hello.cs中增加了对应的代码，执行后提示了startup OK，但似乎Module的内容并没有被正确的引用和执行。

　　请问除了文档中提到的代码以外，还需要配置什么额外的内容么

**Comment by Miyakowww** [comment]
可以先确认一下是否在 mirai-api-http 中配置启用了 WebSocket 且 port 与 http 保持一致。

也可以在 Hello 类中加入以下代码。如果启动时没有显示 `Module initialized`，则 Module 没有被框架所识别，否则可能是消息的接收和处理方面存在问题。
```C#
protected override void Init()
{
    System.Console.WriteLine("Module initialized");
}
```
