### ISSUE TITLE
按照文档配置教程配置的不行

### ISSUE THREAD

**Issue by biu8bo** [Miyakowww/CocoaFramework2#6]
机器人能主动发消息过来，但是路由匹配不执行
![image](https://user-images.githubusercontent.com/61824998/210140600-7175f276-0457-479d-af10-c5621418ee55.png)
![image](https://user-images.githubusercontent.com/61824998/210140544-dbd7911e-eab0-48e2-a398-97c088bdbef9.png)
![image](https://user-images.githubusercontent.com/61824998/210140553-7212d0a6-cbe2-4a63-9182-7f439758c82c.png)

**Comment by biu8bo** [comment]
特性好像没扫描到，不知道是什么原因

**Comment by Miyakowww** [comment]
发送消息使用的是 HTTP 的 API，而接收消息使用的是 WebSocket。可以先检查一下 mirai-api-http 有没有配置启用 WebSocket，也可以重写 Init 方法确认一下 Module 有没有被加载。
